import { MenuModules } from '../../types';
import { SidebarItemsType } from '../../types/sidebar';
import {
   TransactionType,
   User,
   UserPermissionEvent,
   UserScope,
} from '@alienbackoffice/back-front';
import { IconProp } from '@fortawesome/fontawesome-svg-core';
import {
   faBolt,
   faBrowser,
   faCashRegister,
   faChartSimple,
   faCoins,
   faDice,
   faExchange,
   faGears,
   faHexagonExclamation,
   faMemoCircleInfo,
   faMoneyBill,
   faMoneyBillTransfer,
   faMoneyBillTrendUp,
   faTrophy,
   faUsers,
   faUsersBetweenLines,
   faUsersViewfinder,
   faWebhook,
} from '@fortawesome/pro-solid-svg-icons';
import { store } from 'redux/store';

const opId = store.getState().auth.operator;
const brandId = store.getState().auth.currentBrand;
const user = store.getState().auth.user as User;
const pagesSection = [
   {
      href: '/dashboard',
      icon: faBrowser as IconProp,
      title: 'Dashboard',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.DASHBOARD,
      section: 0,
   },
   // reports section
   {
      href: '/tableReports',
      icon: faChartSimple as IconProp,
      title: 'B2B Stats',
      children: [
         {
            href: '/tableReports/operatorReports',
            title: 'All Operators',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
            type: MenuModules.STATS,
         },
      ],
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
      type: MenuModules.STATS,
      section: 1,
   },
   {
      href: '/tableReports',
      icon: faChartSimple as IconProp,
      title: 'B2C Stats',
      children: [
         {
            href: '/tableReports/operatorReports',
            title: 'All Operators',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
            type: MenuModules.STATSC,
         },
      ],
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
      type: MenuModules.STATSC,
      section: 1,
   },
   {
      href: '/reports',
      icon: faHexagonExclamation as IconProp,
      title: 'Reports',
      module: [UserScope.ADMIN, UserScope.SUPERADMIN],
      permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
      type: MenuModules.REPORTS,
      section: 1,
   },
   {
      href: '/quick-reports',
      icon: faHexagonExclamation as IconProp,
      title: 'Quick Reports',
      module: [UserScope.SUPERADMIN],
      permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
      type: MenuModules.QUICKREPORT,
      section: 1,
   },
   {
      href: '/real-time',
      icon: faBolt as IconProp,
      title: 'RealTime',
      module: [UserScope.SUPERADMIN, UserScope.ADMIN],
      type: MenuModules.REALTIME,
      permission: UserPermissionEvent.BACKOFFICE_START_GAME_CORE_REALTIME_REQ,
      section: 1,
   },
   // operators
   {
      href: '/operators',
      icon: faUsersViewfinder as IconProp,
      title: 'Operators',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_OPERATOR_LIST_REQ,
      type: MenuModules.OPERATORS,
      section: 2,
   },
   {
      href: `/brands`,
      icon: faUsers as IconProp,
      title: 'Brands',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
      ],
      type: MenuModules.BRAND,
      permission: UserPermissionEvent.BACKOFFICE_GET_OPERATOR_BRANDS_REQ,
      section: 2,
   },
   {
      href: '/players',
      icon: faUsersBetweenLines as IconProp,
      title: 'app_crash_players',
      badge: 1,
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_PLAYER_LIST_REQ,
      type: MenuModules.PLAYERS,
      section: 2,
   },
   {
      href: '/bets',
      icon: faCoins as IconProp,
      title: 'app_crash_bets',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_BET_LIST_REQ,
      type: MenuModules.BETS,
      section: 2,
   },
   {
      href: '/activities',
      icon: faMemoCircleInfo as IconProp,
      title: 'Player Activities',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.PLAYERACTIVITIES,
      permission: UserPermissionEvent.BACKOFFICE_PLAYER_ACTIVITY_LIST_REQ,
      section: 2,
   },
   {
      href: '/user-activities',
      icon: faMemoCircleInfo as IconProp,
      title: 'User Activities',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
      ],
      type: MenuModules.USERACTIVITIES,
      permission: UserPermissionEvent.BACKOFFICE_USER_ACTIVITY_LIST_REQ,
      section: 2,
   },
   {
      href: '/transactions',
      icon: faMoneyBillTransfer as IconProp,
      title: 'Transactions',
      children: [
         {
            href: `/transactions?type=all`,
            title: 'All transactions',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            type: MenuModules.AllTRANSACTIONS,
            permission: UserPermissionEvent.BACKOFFICE_TRANSACTION_LIST_REQ,
         },
         {
            href: `/transactions?type=${TransactionType.DEPOSIT}`,
            title: 'Deposits',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            type: MenuModules.DEPOSITS,
            permission: UserPermissionEvent.BACKOFFICE_TRANSACTION_LIST_REQ,
         },
         {
            href: `/transactions?type=${TransactionType.WITHDRAW}`,
            title: 'Withdraws',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            type: MenuModules.WITHDRAWS,
            permission: UserPermissionEvent.BACKOFFICE_TRANSACTION_LIST_REQ,
         },
         {
            href: `/transactions?type=${TransactionType.TOPUP}`,
            title: 'Topups',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            type: MenuModules.TOPUPS,
            permission: UserPermissionEvent.BACKOFFICE_TRANSACTION_LIST_REQ,
         },
         {
            href: '/transactions/report',
            title: 'Gateway Report',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
            type: MenuModules.GATEWAYREPORT,
         },
         {
            href: '/transactions/wallet-balance',
            title: 'Wallet Balance',
            module: [
               UserScope.ADMIN,
               UserScope.SUPERADMIN,
               UserScope.OPERATOR,
               UserScope.AFFILIATE,
               UserScope.BRAND,
            ],
            permission: UserPermissionEvent.BACKOFFICE_GET_WALLET_BALANCE_REQ,
            type: MenuModules.WALLETBALANCE,
         },
      ],
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.TRANSACTIONS,
      permission: UserPermissionEvent.BACKOFFICE_TRANSACTION_LIST_REQ,
      section: 2,
   },
   {
      href: '/operator-transactions?type=all',
      icon: faMoneyBillTransfer,
      title: 'Operator Transactions',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.OPERATORTRANSACTIONS,
      permission: UserPermissionEvent.BACKOFFICE_OPERATOR_TRANSACTION_LIST_REQ,
      section: 2,
   },
   {
      href: '/payments',
      icon: faMoneyBill as IconProp,
      title: 'Payment Gateways',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.PAYMENTS,
      permission:
         UserPermissionEvent.BACKOFFICE_GET_ACTIVE_PAYMENT_GATEWAYS_REQ,
      section: 2,
   },
   {
      href: '/cashin-cashout',
      icon: faMoneyBillTrendUp as IconProp,
      title: 'Cashin/Cashout',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
      ],
      type: MenuModules.CASHINGCASHOUT,
      permission: UserPermissionEvent.BACKOFFICE_CASH_IN_CASH_OUT_LIST_REQ,
      section: 2,
   },
   // games
   {
      href: '/games',
      icon: faDice as IconProp,
      title: 'Games',
      module: [UserScope.ADMIN, UserScope.SUPERADMIN],
      permission: UserPermissionEvent.BACKOFFICE_GAME_LIST_REQ,
      type: MenuModules.GAMES,
      section: 3,
   },
   {
      href: '/game-cores',
      icon: faDice as IconProp,
      title: 'Game Cores',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.BRAND,
         UserScope.AFFILIATE,
      ],
      permission: UserPermissionEvent.BACKOFFICE_GAME_CORE_LIST_REQ,
      type: MenuModules.GAMECORES,
      section: 3,
   },
   // tournaments
   {
      href: '/tournament',
      icon: faTrophy as IconProp,
      title: 'Tournament',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.TOURNAMENT,
      permission: [UserScope.OPERATOR, UserScope.BRAND].includes(user?.scope)
         ? UserPermissionEvent.BACKOFFICE_GET_TOURNAMENT_IDS_REQ
         : UserPermissionEvent.BACKOFFICE_GET_TOURNAMENT_LIST_REQ,
      section: 4,
   },
   {
      href: '/v2-Tournament',
      icon: faTrophy as IconProp,
      title: 'Tournament V2',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.TOURNAMENTV2,
      permission: [UserScope.OPERATOR, UserScope.BRAND].includes(user?.scope)
         ? UserPermissionEvent.BACKOFFICE_GET_TOURNAMENT_V2_IDS_REQ
         : UserPermissionEvent.BACKOFFICE_GET_TOURNAMENT_V2_LIST_REQ,
      section: 4,
   },
   //settings
   {
      href: '/operator-config',
      icon: faGears as IconProp,
      title: 'Settings',
      module: [UserScope.OPERATOR],
      type: MenuModules.OPERATORCONFIGS,
      permission: UserPermissionEvent.BACKOFFICE_GET_OPERATOR_REQ,
      section: 5
   },
   {
      href: `/brands/details?id=${opId}&brandId=${brandId}`,
      icon: faGears as IconProp,
      title: 'Settings',
      module: [UserScope.BRAND],
      type: MenuModules.BRANDDETAILS,
      section: 5
   },
   {
      href: '/settings',
      icon: faGears as IconProp,
      title: 'app_settings',
      module: [UserScope.SUPERADMIN],
      type: MenuModules.SETTING,
      permission: UserPermissionEvent.BACKOFFICE_GET_PERMISSIONS_REQ,
      section: 5
   },
   {
      href: '/users',
      icon: faDice as IconProp,
      title: 'app_users',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      permission: UserPermissionEvent.BACKOFFICE_USER_LIST_REQ,
      type: MenuModules.USERS,
      section: 5
   },
   {
      href: '/exchange',
      icon: faExchange as IconProp,
      title: 'Exchange Rates',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.EXCHANGERATES,
      permission: UserPermissionEvent.BACKOFFICE_GET_CURRENCIES_REQ,
      section: 5
   },
   {
      href: '/devOps',
      icon: faGears as IconProp,
      title: 'DevOps',
      children: [
         {
            href: `/devOps/cloudFlare`,
            title: 'CloudFlare',
            module: [UserScope.SUPERADMIN, UserScope.ADMIN],
            type: MenuModules.CLOUDFLARE,
            permission: UserPermissionEvent.BACKOFFICE_DNS_RECORD_LIST_REQ,
         },
      ],
      module: [UserScope.SUPERADMIN, UserScope.ADMIN],
      type: MenuModules.DEVOPS,
      permission: UserPermissionEvent.BACKOFFICE_DNS_RECORD_LIST_REQ,
      section: 5
   },
   {
      href: '/logs',
      icon: faWebhook as IconProp,
      title: 'Logs',
      module: [
         UserScope.ADMIN,
         UserScope.SUPERADMIN,
         UserScope.OPERATOR,
         UserScope.AFFILIATE,
         UserScope.BRAND,
      ],
      type: MenuModules.LOGS,
      permission: UserPermissionEvent.BACKOFFICE_GET_WEBHOOK_LOG_LIST_REQ,
      section: 5
   },
   // {
   //    href: '/gameV2',
   //    icon: faDice as IconProp,
   //    title: 'Games V2',
   //    module: [
   //       UserScope.ADMIN,
   //       UserScope.SUPERADMIN,
   //       UserScope.OPERATOR,
   //       UserScope.BRAND,
   //    ],
   //    permission: UserPermissionEvent.BACKOFFICE_GAMEV2_LIST_REQ,
   //    type: MenuModules.GAMESV2,
   // },
   // {
   //    href: '/operator-games',
   //    icon: faDice,
   //    title: 'Games',
   //    module: [UserScope.OPERATOR],
   //    type: MenuModules.OPERATORGAMES,
   //    permission: UserPermissionEvent.BACKOFFICE_OPERATOR_GAME_LIST_REQ,
   // },
   // {
   //    href: '/admin-reports',
   //    icon: faHexagonExclamation as IconProp,
   //    title: 'Admin Reports',
   //    module: [UserScope.SUPERADMIN],
   //    permission: UserPermissionEvent.BACKOFFICE_GET_FINANCIAL_REPORT_REQ,
   //    type: MenuModules.REPORTS,
   // },
] as SidebarItemsType[];

const navItems = [
   {
      title: '',
      pages: pagesSection,
   },
];
export default navItems;
